import '../src/js/pagination-result';
import '../src/js/to-top-btn';
import '../src/js/api-fetch';
import '../src/js/spiner';
import '../src/js/localstorage';
import '../src/js/modal';
import '../src/js/teamModal';
import '../src/js/theme-choice';
import '../src/js/onModalOpen';
import { renderMainPage } from '../src/js/api-fetch';
renderMainPage();